version: '3'
volumes:
    data:
services:
    db:
        image: postgres:9.6
        volumes:
            - data:/var/lib/postgresql/data
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    frontend:
        image: nginx:1.13
        volumes:
            - ./web:/usr/share/nginx/html
        ports:
            - 80:80